
spring:
  redis:
    host: localhost
    port: 6379
    password: lmk793694
    timeout: 1000
    jedis:
      pool:
        max-wait: 200
        max-idle: 10
        min-idle: -1
server:
  port: 8088
